### ISSUE TITLE
Require frozen string literals

### ISSUE THREAD

**Issue by breese524** [RamseyInHouse/ramsey-cop#29]
Should we require the magic comment to freeze string literals?
`# frozen_string_literal: true`

Presumably this will not be necessary when we begin using Ruby 3.0.

👍  for yes (continue with the default setting), 👎  for no (change the default setting)

**Comment by ahcarpenter** [comment]
Hey sirs, to clarify here, we would want to be using immutable strings wherever possible, but just don't want to encourage people use one particular approach?

Also, fwiw, not sure what sorts of themes everyone is using in their editor, but I absolutely love https://www.monokai.pro/. Def a fan of the default colors and style in which it renders in terms of how it integrates with the visual importance other tokens as for cases when I _had_ wanted to have comments in the code, I feel like it's most definitely helped to be able to filter those out

![screen shot 2018-05-25 at 8 55 08 am](https://user-images.githubusercontent.com/574903/40548122-70aca6bc-5ff9-11e8-9b3e-fc8e2c702c88.png)

**Comment by breese524** [comment]
@ahcarpenter For me it's not so much about an extra line at the top of the file, it's the fact that this is a temporary change until some arbitrary date when we start using Ruby 3.0. If there was a way to set it for the whole project, in one place, that would be better but, I don't see that anywhere.
