### ISSUE TITLE
Discuss adjusting Metrics/MethodLength and Metrics/AbcSize

### ISSUE THREAD

**Issue by philharvey** [RamseyInHouse/ramsey-cop#71]
The current MethodLength (max 10) and AbcSize (max 15), which come from Rubocop's default settings, seem quite low. For projects that enforce that all checks pass, it feels like these two are creating a perverse incentive to break code apart in potentially unhelpful ways.

I'd like to discuss increasing these to a potentially higher value. I welcome your constructive observations, objections, and suggestions.

**Comment by mellowfish** [comment]
I personally like the pain of these limitations. I feel like my code comes out cleaner on the whole as a result. 

However, I am also *very* comfortable throwing `# rubocop:disable Metrics/Whatever` on a method definition if I can't see how to cleanly refactor it.

**Comment by jwsloan** [comment]
I mostly fall inline with @mellowfish on this. I would be fine with increasing them some, I just think it would be hard to figure out what the right size is.

**Comment by mellowfish** [comment]
FWIW, AbcSize is often much harder to fix in a reasonable way. If we were going to only update one, I would pick that one.

**Comment by jasonyork** [comment]
I've also found that (while sometimes annoying) I end up with better, more readable code when I break down larger methods to smaller ones... to me, the current setting (for MethodLength) is good.

This isn't perfect metric, but based on a github search, it doesn't appear that it gets overridden all that often:
https://github.com/search?l=&q=org%3Alampo+%22rubocop%3Adisable+Metrics%2FMethodLength%22&type=Code

For `AbcSize` I might be more apt to increase that a little, but I do find a lot of value in the metric forcing me to take another look at my methods to simplify them.

Current overrides:
https://github.com/search?q=org%3Alampo+%22rubocop%3Adisable+Metrics%2FAbcSize%22&type=Code

I would definitely be in favor of excluding some additional folders (like migrations) from these metrics though.

**Comment by rickpeyton** [comment]
I also feel that the current MethodLength value is good. Like Jason, I would not be opposed to excluding more folders by default. And, like Christopher, I feel the `rubocop:disable` works well when needed. It makes it easy to have a conversation in PR if necessary.

Sandi Metz and Thoughtbot both regularly teach to strive for 5 lines or less. I am not advocating for going even more strict, but I think the current value at least keeps that awareness top of mind.

I feel less strongly about `AbcSize`

**Comment by philharvey** [comment]
Thanks everyone for your input. I'll stick with the defaults and override on an as-needed basis.
