### ISSUE TITLE
Add rubocop-rails as a dependancy

### ISSUE THREAD

**Issue by ethan-dowler** [RamseyInHouse/ramsey-cop#81]
## Expected Behavior
- ramsey-cop will lint my rails code

## Actual Behavior
- rubocop no longer lints rails code by default; you have to add rubocop-rails

## Steps to Reproduce Behavior
- install ramsey-cop gem
<img width="822" alt="Screen Shot 2019-07-01 at 12 48 59 PM" src="https://user-images.githubusercontent.com/32302647/60456879-2bc87000-9c00-11e9-88a1-7bdcf80114f8.png">

## Specifications
(e.g. versions, operating system, hardware, etc.)

**Comment by jlw** [comment]
@ethan-dowler - since RamseyCop is used by gems (and possibly other Ruby, non-Rails projects), it seems like rubocop-rails should be added at the project level.

There might even be a case for a separate set of ramsey-cop-rails overrides...

**Comment by mellowfish** [comment]
Yeah, this should be handled by a separate gem like `ramsey_cop_rails` or something.
